"use client";

import Link from "next/link";
import { useState, useTransition } from "react";
import { CalendarDays, Check, ChevronRight, CircleAlert, Download, Edit3, Flag, Layers3, Map, Plus, Target, Trash2, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { createGoalAction, createMonthAction, createPhaseAction, createWeekAction, createYearAction, deleteGoalAction, deleteMonthAction, deletePhaseAction, deleteWeekAction, deleteYearAction, updateGoalAction, updateMonthAction, updatePhaseAction, updateWeekAction, updateYearAction } from "@/app/actions/roadmap-actions";
import { EmptyState } from "@/components/feedback/feedback-patterns";
import { ProgressBar } from "@/components/progress/progress-visuals";
import { Badge } from "@/components/ui/badge";
import { Button, IconButton } from "@/components/ui/button";
import type { RoadmapData, RoadmapGoal, RoadmapMonth, RoadmapPhase, RoadmapStatus, RoadmapWeek, RoadmapYear } from "@/features/roadmap/roadmap-data";

type EntityKind = "goal" | "year" | "phase" | "month" | "week";
type EntityRecord = RoadmapGoal | RoadmapYear | RoadmapPhase | RoadmapMonth | RoadmapWeek;
type FormState = { title: string; description: string; objective: string; status: RoadmapStatus; horizonYears: string; targetDate: string; year: string; goalId: string; roadmapYearId: string; roadmapPhaseId: string; roadmapMonthId: string; monthStart: string; weekStart: string; weekEnd: string; sortOrder: string };

const statusLabels: Record<RoadmapStatus, string> = { planned: "Planned", active: "Active", completed: "Completed", archived: "Archived" };
const statusTones: Record<RoadmapStatus, "neutral" | "primary" | "success" | "violet"> = { planned: "neutral", active: "primary", completed: "success", archived: "violet" };
const roadmapStatuses: RoadmapStatus[] = ["planned", "active", "completed", "archived"];

function emptyForm(status: RoadmapStatus = "planned"): FormState { return { title: "", description: "", objective: "", status, horizonYears: "", targetDate: "", year: String(new Date().getFullYear()), goalId: "", roadmapYearId: "", roadmapPhaseId: "", roadmapMonthId: "", monthStart: `${new Date().toISOString().slice(0, 7)}-01`, weekStart: new Date().toISOString().slice(0, 10), weekEnd: "", sortOrder: "0" }; }
function statusLabel(status: RoadmapStatus) { return <Badge tone={statusTones[status]} dot>{statusLabels[status]}</Badge>; }
function formatDate(value: string | null) { return value ? new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeZone: "UTC" }).format(new Date(`${value}T12:00:00Z`)) : null; }
function progressFromChildren(statuses: RoadmapStatus[], ownStatus: RoadmapStatus) { return statuses.length ? Math.round((statuses.filter((status) => status === "completed").length / statuses.length) * 100) : ownStatus === "completed" ? 100 : 0; }
function inputClass() { return "mt-2 min-h-11 w-full rounded-xl border border-[var(--line-strong)] bg-[var(--surface)] px-3 text-sm outline-none focus:border-[var(--primary)] focus:ring-2 focus:ring-[var(--primary-tint)]"; }

function progressLabel(value: number, count: number, noun: string) { return count ? `${value}% · ${count} ${noun}` : `${value}% · status based`; }

function formFromEntity(kind: EntityKind, item: EntityRecord): FormState {
  const form = emptyForm(item.status);
  if (kind === "goal") { const goal = item as RoadmapGoal; return { ...form, title: goal.title, description: goal.description ?? "", horizonYears: goal.horizonYears ? String(goal.horizonYears) : "", targetDate: goal.targetDate ?? "" }; }
  if (kind === "year") { const year = item as RoadmapYear; return { ...form, title: year.title, objective: year.objective ?? "", year: String(year.year), goalId: year.goalId ?? "" }; }
  if (kind === "phase") { const phase = item as RoadmapPhase; return { ...form, title: phase.title, objective: phase.objective ?? "", roadmapYearId: phase.roadmapYearId, sortOrder: String(phase.sortOrder) }; }
  if (kind === "month") { const month = item as RoadmapMonth; return { ...form, title: month.title, objective: month.objective ?? "", roadmapPhaseId: month.roadmapPhaseId, monthStart: month.monthStart }; }
  const week = item as RoadmapWeek;
  return { ...form, objective: week.objective ?? "", roadmapMonthId: week.roadmapMonthId, weekStart: week.weekStart, weekEnd: week.weekEnd ?? "" };
}

function kindLabel(kind: EntityKind) { return kind === "goal" ? "goal" : kind; }
function recordTitle(kind: EntityKind, item: EntityRecord) {
  return kind === "week" ? (item as RoadmapWeek).objective || `Week of ${(item as RoadmapWeek).weekStart}` : (item as RoadmapGoal | RoadmapYear | RoadmapPhase | RoadmapMonth).title;
}

function RoadmapForm({ kind, initial, data, editing, pending, error, onClose, onSubmit }: { kind: EntityKind; initial: FormState; data: RoadmapData; editing: boolean; pending: boolean; error: string | null; onClose: () => void; onSubmit: (form: FormState) => void }) {
  const [form, setForm] = useState(initial);
  const set = (key: keyof FormState, value: string) => setForm((current) => ({ ...current, [key]: value }));
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-[rgba(16,26,51,0.5)] p-0 sm:items-center sm:p-6" role="presentation"><div className="max-h-[94vh] w-full overflow-y-auto rounded-t-3xl bg-[var(--surface)] p-6 shadow-[var(--shadow-md)] sm:max-w-xl sm:rounded-3xl" role="dialog" aria-modal="true" aria-labelledby="roadmap-form-title"><div className="flex items-start justify-between gap-4"><div><Badge tone="primary">{editing ? `Edit ${kindLabel(kind)}` : `New ${kindLabel(kind)}`}</Badge><h2 id="roadmap-form-title" className="mt-3 text-2xl font-semibold tracking-[-0.04em]">{editing ? "Keep the next level clear." : "Add the next level of the plan."}</h2></div><IconButton onClick={onClose} aria-label="Close roadmap form"><X size={19} /></IconButton></div><form className="mt-6 space-y-4" onSubmit={(event) => { event.preventDefault(); onSubmit(form); }}>
    {kind !== "week" ? <label className="block text-sm font-semibold">{kind === "goal" ? "Goal title" : kind === "year" ? "Year title" : kind === "phase" ? "Phase title" : "Month title"}<input className={inputClass()} value={form.title} onChange={(event) => set("title", event.target.value)} maxLength={160} required placeholder={kind === "goal" ? "Build a durable million-dollar business" : "The next meaningful stage"} /></label> : null}
    {kind === "goal" ? <><label className="block text-sm font-semibold">Notes<textarea className={`${inputClass()} min-h-24 py-3`} value={form.description} onChange={(event) => set("description", event.target.value)} maxLength={1000} /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-semibold">Horizon years<input className={inputClass()} type="number" min="1" max="100" value={form.horizonYears} onChange={(event) => set("horizonYears", event.target.value)} placeholder="7" /></label><label className="block text-sm font-semibold">Target date<input className={inputClass()} type="date" value={form.targetDate} onChange={(event) => set("targetDate", event.target.value)} /></label></div></> : null}
    {kind === "year" ? <><label className="block text-sm font-semibold">Year<input className={inputClass()} type="number" min="2000" max="2200" value={form.year} onChange={(event) => set("year", event.target.value)} required /></label><label className="block text-sm font-semibold">Objective<textarea className={`${inputClass()} min-h-24 py-3`} value={form.objective} onChange={(event) => set("objective", event.target.value)} maxLength={500} /></label><label className="block text-sm font-semibold">Parent goal<select className={inputClass()} value={form.goalId} onChange={(event) => set("goalId", event.target.value)}><option value="">No parent goal</option>{data.goals.map((goal) => <option key={goal.id} value={goal.id}>{goal.title}</option>)}</select></label></> : null}
    {kind === "phase" ? <><label className="block text-sm font-semibold">Objective<textarea className={`${inputClass()} min-h-24 py-3`} value={form.objective} onChange={(event) => set("objective", event.target.value)} maxLength={500} /></label><label className="block text-sm font-semibold">Roadmap year<select className={inputClass()} value={form.roadmapYearId} onChange={(event) => set("roadmapYearId", event.target.value)} required><option value="">Choose a year</option>{data.years.map((year) => <option key={year.id} value={year.id}>{year.year} · {year.title}</option>)}</select></label><label className="block text-sm font-semibold">Order<input className={inputClass()} type="number" min="0" value={form.sortOrder} onChange={(event) => set("sortOrder", event.target.value)} /></label></> : null}
    {kind === "month" ? <><label className="block text-sm font-semibold">Objective<textarea className={`${inputClass()} min-h-24 py-3`} value={form.objective} onChange={(event) => set("objective", event.target.value)} maxLength={500} /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-semibold">Month starts<input className={inputClass()} type="date" value={form.monthStart} onChange={(event) => set("monthStart", event.target.value)} required /></label><label className="block text-sm font-semibold">Parent phase<select className={inputClass()} value={form.roadmapPhaseId} onChange={(event) => set("roadmapPhaseId", event.target.value)} required><option value="">Choose a phase</option>{data.phases.map((phase) => <option key={phase.id} value={phase.id}>{phase.title}</option>)}</select></label></div></> : null}
    {kind === "week" ? <><label className="block text-sm font-semibold">Weekly outcome<textarea className={`${inputClass()} min-h-24 py-3`} value={form.objective} onChange={(event) => set("objective", event.target.value)} maxLength={500} placeholder="What outcome makes this week count?" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-semibold">Week starts<input className={inputClass()} type="date" value={form.weekStart} onChange={(event) => set("weekStart", event.target.value)} required /></label><label className="block text-sm font-semibold">Week ends<input className={inputClass()} type="date" value={form.weekEnd} onChange={(event) => set("weekEnd", event.target.value)} /></label></div><label className="block text-sm font-semibold">Parent month<select className={inputClass()} value={form.roadmapMonthId} onChange={(event) => set("roadmapMonthId", event.target.value)} required><option value="">Choose a month</option>{data.months.map((month) => <option key={month.id} value={month.id}>{month.monthStart} · {month.title}</option>)}</select></label></> : null}
    <label className="block text-sm font-semibold">Status<select className={inputClass()} value={form.status} onChange={(event) => set("status", event.target.value)}>{roadmapStatuses.map((status) => <option key={status} value={status}>{statusLabels[status]}</option>)}</select></label>
    {error ? <p className="flex items-start gap-2 rounded-xl bg-[var(--danger-tint)] p-3 text-sm leading-5 text-[var(--danger)]" role="alert"><CircleAlert size={16} className="mt-0.5 shrink-0" />{error}</p> : null}<div className="flex flex-wrap justify-end gap-3 pt-2"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit" disabled={pending}>{pending ? "Saving..." : editing ? "Save changes" : `Create ${kindLabel(kind)}`}<Check size={16} /></Button></div>
  </form></div></div>;
}

export function RoadmapPage({ data }: { data: RoadmapData }) {
  const router = useRouter();
  const [selectedGoalId, setSelectedGoalId] = useState<string | null>(null);
  const [selectedYearId, setSelectedYearId] = useState<string | null>(null);
  const [selectedPhaseId, setSelectedPhaseId] = useState<string | null>(null);
  const [selectedMonthId, setSelectedMonthId] = useState<string | null>(null);
  const [selectedWeekId, setSelectedWeekId] = useState<string | null>(null);
  const [modal, setModal] = useState<{ kind: EntityKind; item?: EntityRecord; initial?: FormState } | null>(null);
  const [confirm, setConfirm] = useState<{ kind: EntityKind; id: string; title: string } | null>(null);
  const [error, setError] = useState<string | null>(data.error);
  const [success, setSuccess] = useState<string | null>(null);
  const [pending, startTransition] = useTransition();

  const selectedGoal = data.goals.find((goal) => goal.id === selectedGoalId) ?? data.goals.find((goal) => goal.status === "active") ?? data.goals[0] ?? null;
  const years = data.years.filter((year) => year.goalId === selectedGoal?.id || year.goalId === null);
  const selectedYear = data.years.find((year) => year.id === selectedYearId) ?? years.find((year) => year.status === "active") ?? years[0] ?? null;
  const phases = data.phases.filter((phase) => phase.roadmapYearId === selectedYear?.id);
  const selectedPhase = data.phases.find((phase) => phase.id === selectedPhaseId) ?? phases.find((phase) => phase.status === "active") ?? phases[0] ?? null;
  const months = data.months.filter((month) => month.roadmapPhaseId === selectedPhase?.id);
  const selectedMonth = data.months.find((month) => month.id === selectedMonthId) ?? months.find((month) => month.status === "active") ?? months[0] ?? null;
  const weeks = data.weeks.filter((week) => week.roadmapMonthId === selectedMonth?.id);

  function openCreate(kind: EntityKind) {
    const form = emptyForm(kind === "goal" ? "active" : "planned");
    if (kind === "year") form.goalId = selectedGoal?.id ?? "";
    if (kind === "phase") form.roadmapYearId = selectedYear?.id ?? "";
    if (kind === "month") form.roadmapPhaseId = selectedPhase?.id ?? "";
    if (kind === "week") form.roadmapMonthId = selectedMonth?.id ?? "";
    setError(null); setSuccess(null); setModal({ kind, item: undefined, initial: form });
  }

  function openEdit(kind: EntityKind, item: EntityRecord) { setError(null); setSuccess(null); setModal({ kind, item }); }

  function save(kind: EntityKind, form: FormState) {
    setError(null);
    startTransition(async () => {
      let result;
      if (kind === "goal") { const input = { title: form.title, description: form.description, horizonYears: form.horizonYears ? Number(form.horizonYears) : undefined, targetDate: form.targetDate || undefined, status: form.status }; result = modal?.item ? await updateGoalAction(modal.item.id, input) : await createGoalAction(input); }
      else if (kind === "year") { const input = { goalId: form.goalId || undefined, year: Number(form.year), title: form.title, objective: form.objective, status: form.status }; result = modal?.item ? await updateYearAction(modal.item.id, input) : await createYearAction(input); }
      else if (kind === "phase") { const input = { roadmapYearId: form.roadmapYearId, title: form.title, objective: form.objective, sortOrder: Number(form.sortOrder), status: form.status }; result = modal?.item ? await updatePhaseAction(modal.item.id, input) : await createPhaseAction(input); }
      else if (kind === "month") { const input = { roadmapPhaseId: form.roadmapPhaseId, monthStart: form.monthStart, title: form.title, objective: form.objective, status: form.status }; result = modal?.item ? await updateMonthAction(modal.item.id, input) : await createMonthAction(input); }
      else { const input = { roadmapMonthId: form.roadmapMonthId, weekStart: form.weekStart, weekEnd: form.weekEnd || undefined, objective: form.objective, status: form.status }; result = modal?.item ? await updateWeekAction(modal.item.id, input) : await createWeekAction(input); }
      if (!result.ok) { setError(result.error); return; }
      setModal(null); setSuccess(`${kindLabel(kind)} ${modal?.item ? "updated" : "created"}.`); router.refresh();
    });
  }

  function remove(kind: EntityKind, id: string) {
    setError(null); startTransition(async () => {
      const result = kind === "goal" ? await deleteGoalAction(id) : kind === "year" ? await deleteYearAction(id) : kind === "phase" ? await deletePhaseAction(id) : kind === "month" ? await deleteMonthAction(id) : await deleteWeekAction(id);
      if (!result.ok) { setError(result.error); return; }
      setConfirm(null); setSuccess(`${kindLabel(kind)} deleted.`); router.refresh();
    });
  }

  if (!data.authenticated) return <div className="mx-auto max-w-3xl px-5 py-12 sm:px-8 lg:px-12"><Badge tone="primary">Roadmap</Badge><h1 className="mt-4 text-4xl font-semibold tracking-[-0.05em]">Sign in to build the plan.</h1><p className="mt-4 max-w-xl text-base leading-7 text-[var(--muted)]">Your roadmap is private to your authenticated workspace.</p></div>;

  const goalProgress = selectedGoal ? progressFromChildren(years.map((year) => year.status), selectedGoal.status) : 0;
  const yearProgress = selectedYear ? progressFromChildren(phases.map((phase) => phase.status), selectedYear.status) : 0;
  const phaseProgress = selectedPhase ? progressFromChildren(months.map((month) => month.status), selectedPhase.status) : 0;
  const monthProgress = selectedMonth ? progressFromChildren(weeks.map((week) => week.status), selectedMonth.status) : 0;
  const context = [selectedGoal?.status === "active" ? selectedGoal.title : null, selectedYear?.status === "active" ? selectedYear.title : null, selectedPhase?.status === "active" ? selectedPhase.title : null, selectedMonth?.status === "active" ? selectedMonth.title : null, weeks.find((week) => week.status === "active")?.objective ?? null].filter(Boolean);

  return <div className="mx-auto max-w-[1500px] px-5 py-8 sm:px-8 lg:px-12 lg:py-10"><header className="flex flex-col justify-between gap-6 border-b border-[var(--line)] pb-8 lg:flex-row lg:items-end"><div><div className="flex flex-wrap items-center gap-3"><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-[var(--violet)]"><Map size={14} />Long-term direction</p><Badge tone="violet" dot>Roadmap</Badge></div><h1 className="mt-4 max-w-3xl text-4xl font-semibold tracking-[-0.06em] sm:text-5xl">Make the path visible.</h1><p className="mt-3 max-w-2xl text-base leading-7 text-[var(--muted)]">Connect the outcome to the next week without pretending progress is further along than it is.</p></div><div className="flex flex-wrap gap-3"><Link href="/planning/week/new" className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-[var(--primary)] px-4 text-sm font-semibold text-white transition hover:bg-[var(--primary-hover)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--primary)] focus-visible:ring-offset-2"><Plus size={16} />Create week</Link><Link href="/roadmap/import" className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-[var(--line-strong)] bg-[var(--surface)] px-4 text-sm font-semibold text-[var(--ink)] transition hover:border-[var(--primary-soft)] hover:text-[var(--primary)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--primary)] focus-visible:ring-offset-2"><Download size={16} />Import</Link><Button type="button" onClick={() => openCreate("goal")}><Plus size={17} />New goal</Button></div></header>
    {error ? <div className="mt-6 flex items-start gap-2 rounded-2xl bg-[var(--danger-tint)] p-4 text-sm text-[var(--danger)]" role="alert"><CircleAlert size={17} className="mt-0.5 shrink-0" />{error}</div> : null}{success ? <div className="mt-6 flex items-center gap-2 rounded-2xl bg-[var(--success-tint)] p-4 text-sm text-[var(--success)]" role="status"><Check size={17} />{success}</div> : null}
    {data.goals.length === 0 ? <section className="mt-8"><EmptyState title="Start with the outcome." detail="Create the configurable goal that gives every year, phase, month, and week a direction." /><div className="mt-5 flex justify-center"><Button type="button" onClick={() => openCreate("goal")}><Target size={17} />Create your first goal</Button></div></section> : <><section className="mt-8 grid gap-4 lg:grid-cols-[0.72fr_1.28fr]"><div className="rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-5 shadow-[var(--shadow-sm)]"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[var(--muted)]">Goals</p><h2 className="mt-2 text-xl font-semibold">The destination</h2></div><Badge tone="primary">{data.goals.length}</Badge></div><div className="mt-5 space-y-2">{data.goals.map((goal) => <button type="button" key={goal.id} onClick={() => { setSelectedGoalId(goal.id); setSelectedYearId(null); setSelectedPhaseId(null); setSelectedMonthId(null); }} className={`w-full rounded-2xl border p-4 text-left transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--primary)] ${selectedGoal?.id === goal.id ? "border-[var(--primary-soft)] bg-[var(--primary-tint)]" : "border-[var(--line)] hover:border-[var(--line-strong)]"}`}><div className="flex items-start justify-between gap-3"><span className="font-semibold">{goal.title}</span><ChevronRight size={17} className="shrink-0 text-[var(--muted)]" /></div><div className="mt-2 flex flex-wrap items-center gap-2">{statusLabel(goal.status)}{goal.targetDate ? <span className="text-xs text-[var(--muted)]">Target {formatDate(goal.targetDate)}</span> : null}</div></button>)}</div></div>
      {selectedGoal ? <div className="rounded-3xl border border-[var(--primary-soft)] bg-[var(--surface)] p-6 shadow-[var(--shadow-md)] sm:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.15em] text-[var(--primary)]"><Flag size={14} />Primary outcome</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.05em]">{selectedGoal.title}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--muted)]">{selectedGoal.description || "Add notes that make the outcome concrete and useful."}</p></div><div className="flex shrink-0 gap-2"><IconButton onClick={() => openEdit("goal", selectedGoal)} aria-label="Edit goal"><Edit3 size={17} /></IconButton><IconButton onClick={() => setConfirm({ kind: "goal", id: selectedGoal.id, title: selectedGoal.title })} aria-label="Delete goal"><Trash2 size={17} /></IconButton></div></div><div className="mt-7 grid gap-4 sm:grid-cols-3"><div><p className="text-xs text-[var(--muted)]">Status</p><div className="mt-2">{statusLabel(selectedGoal.status)}</div></div><div><p className="text-xs text-[var(--muted)]">Horizon</p><p className="mt-2 font-semibold">{selectedGoal.horizonYears ? `${selectedGoal.horizonYears} years` : "Not set"}</p></div><div><p className="text-xs text-[var(--muted)]">Target date</p><p className="mt-2 font-semibold">{formatDate(selectedGoal.targetDate) ?? "Not set"}</p></div></div><div className="mt-7"><ProgressBar value={goalProgress} label={progressLabel(goalProgress, years.length, "years complete")} tone="primary" /></div></div> : null}</section>
      <HierarchySection kind="year" title="Years" eyebrow="Trajectory" icon={<CalendarDays size={16} />} items={years} selectedId={selectedYear?.id ?? null} progress={yearProgress} onSelect={(id) => { setSelectedYearId(id); setSelectedPhaseId(null); setSelectedMonthId(null); setSelectedWeekId(null); }} onCreate={() => openCreate("year")} onEdit={(item) => openEdit("year", item)} onDelete={(item) => setConfirm({ kind: "year", id: item.id, title: recordTitle("year", item) })} emptyText="Add a year to give the long-term outcome a next horizon." />
      {selectedYear ? <HierarchySection kind="phase" title="Phases" eyebrow={`Inside ${selectedYear.title}`} icon={<Layers3 size={16} />} items={phases} selectedId={selectedPhase?.id ?? null} progress={phaseProgress} onSelect={(id) => { setSelectedPhaseId(id); setSelectedMonthId(null); setSelectedWeekId(null); }} onCreate={() => openCreate("phase")} onEdit={(item) => openEdit("phase", item)} onDelete={(item) => setConfirm({ kind: "phase", id: item.id, title: recordTitle("phase", item) })} emptyText="Add a phase to turn this year into a sequence of meaningful stages." /> : null}
      {selectedPhase ? <HierarchySection kind="month" title="Months" eyebrow={`Inside ${selectedPhase.title}`} icon={<CalendarDays size={16} />} items={months} selectedId={selectedMonth?.id ?? null} progress={monthProgress} onSelect={(id) => { setSelectedMonthId(id); setSelectedWeekId(null); }} onCreate={() => openCreate("month")} onEdit={(item) => openEdit("month", item)} onDelete={(item) => setConfirm({ kind: "month", id: item.id, title: recordTitle("month", item) })} emptyText="Add a month to make this phase actionable." /> : null}
      {selectedMonth ? <HierarchySection kind="week" title="Weeks" eyebrow={`Inside ${selectedMonth.title}`} icon={<CalendarDays size={16} />} items={weeks} selectedId={selectedWeekId} progress={monthProgress} onSelect={setSelectedWeekId} onCreate={() => openCreate("week")} onEdit={(item) => openEdit("week", item)} onDelete={(item) => setConfirm({ kind: "week", id: item.id, title: recordTitle("week", item) })} emptyText="Add a weekly outcome, then link tasks to it from Tasks." /> : null}
      <section className="mt-8 rounded-3xl border border-[var(--violet-tint)] bg-[var(--violet-tint)] p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[var(--violet)]">Current planning context</p><h2 className="mt-3 text-2xl font-semibold tracking-[-0.04em]">{context.length ? context.join(" → ") : "Activate one level to set the current context."}</h2><p className="mt-3 text-sm leading-6 text-[var(--ink-soft)]">Only records marked active are presented as current. Weekly outcomes can connect directly to daily tasks from the Tasks workspace.</p></section></>}
    {modal ? <RoadmapForm kind={modal.kind} initial={modal.item ? formFromEntity(modal.kind, modal.item) : modal.initial ?? emptyForm()} data={data} editing={Boolean(modal.item)} pending={pending} error={error} onClose={() => setModal(null)} onSubmit={(form) => save(modal.kind, form)} /> : null}
    {confirm ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-[rgba(16,26,51,0.5)] p-5" role="presentation"><div className="w-full max-w-md rounded-3xl bg-[var(--surface)] p-6 shadow-[var(--shadow-md)]" role="dialog" aria-modal="true" aria-labelledby="roadmap-delete-title"><h2 id="roadmap-delete-title" className="text-xl font-semibold">Delete this {kindLabel(confirm.kind)}?</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">“{confirm.title}” may also remove its nested roadmap records because the existing database relationships cascade deletes.</p><div className="mt-6 flex justify-end gap-3"><Button type="button" variant="secondary" onClick={() => setConfirm(null)}>Cancel</Button><Button type="button" variant="danger" onClick={() => remove(confirm.kind, confirm.id)} disabled={pending}>{pending ? "Deleting..." : "Delete"}<Trash2 size={16} /></Button></div></div></div> : null}
  </div>;
}

function HierarchySection({ kind, title, eyebrow, icon, items, selectedId, progress, onSelect, onCreate, onEdit, onDelete, emptyText }: { kind: EntityKind; title: string; eyebrow: string; icon: React.ReactNode; items: EntityRecord[]; selectedId: string | null; progress: number; onSelect: (id: string) => void; onCreate: () => void; onEdit: (item: EntityRecord) => void; onDelete: (item: EntityRecord) => void; emptyText: string }) {
  return <section className="mt-8" aria-labelledby={`${kind}-heading`}><div className="flex flex-col justify-between gap-4 border-b border-[var(--line)] pb-4 sm:flex-row sm:items-end"><div><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.15em] text-[var(--muted)]">{icon}{eyebrow}</p><h2 id={`${kind}-heading`} className="mt-2 text-2xl font-semibold tracking-[-0.04em]">{title}</h2><div className="mt-3 max-w-sm"><ProgressBar value={progress} label="Selected level progress" tone={kind === "phase" ? "violet" : kind === "week" ? "success" : "primary"} /></div></div><Button variant="secondary" onClick={onCreate}><Plus size={16} />Add {kindLabel(kind)}</Button></div>{items.length === 0 ? <div className="mt-4 rounded-2xl border border-dashed border-[var(--line-strong)] bg-[var(--surface)] p-6 text-sm text-[var(--muted)]">{emptyText}</div> : <div className="mt-4 grid gap-3 lg:grid-cols-2">{items.map((item) => <article key={item.id} className={`rounded-2xl border bg-[var(--surface)] p-5 shadow-[var(--shadow-sm)] transition ${selectedId === item.id ? "border-[var(--primary-soft)] shadow-[var(--shadow-md)]" : "border-[var(--line)]"}`}><button type="button" onClick={() => onSelect(item.id)} className="w-full text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--primary)]"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{kind === "week" ? (item as RoadmapWeek).objective || `Week of ${(item as RoadmapWeek).weekStart}` : (item as EntityRecord & { title: string }).title}</h3><p className="mt-1 text-sm text-[var(--muted)]">{kind === "week" ? `${(item as RoadmapWeek).weekStart}${(item as RoadmapWeek).weekEnd ? ` → ${(item as RoadmapWeek).weekEnd}` : ""}` : (item as EntityRecord & { objective?: string | null }).objective || "No objective added yet."}</p></div><ChevronRight size={17} className="shrink-0 text-[var(--muted)]" /></div></button><div className="mt-4 flex items-center justify-between gap-3">{statusLabel(item.status)}<div className="flex items-center gap-1"><IconButton onClick={() => onEdit(item)} aria-label={`Edit ${kindLabel(kind)}`}><Edit3 size={15} /></IconButton><IconButton onClick={() => onDelete(item)} aria-label={`Delete ${kindLabel(kind)}`}><Trash2 size={15} /></IconButton></div></div>{kind !== "week" ? <div className="mt-3"><ProgressBar value={progressFromChildren([], item.status)} label={statusLabels[item.status]} tone={item.status === "completed" ? "success" : kind === "phase" ? "violet" : "primary"} /></div> : null}</article>)}</div>}</section>;
}
